<?php

namespace FactureBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FactureVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureVenteRepository extends EntityRepository
{
}
