<?php

namespace VenteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeVenteRepository extends EntityRepository
{
}
