<?php

namespace VenteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LigneVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneVenteRepository extends EntityRepository
{
}
