<?php

namespace BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MouvementProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementProduitRepository extends EntityRepository
{
}
