<?php

namespace BackBundle\Repository;

use BackBundle\Entity\Utilisateur;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UtilisateurRepository extends EntityRepository
{



}



