<?php

namespace AchatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeAchatRepository extends EntityRepository
{
}
