<?php

namespace AchatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FourCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FourCatRepository extends EntityRepository
{
}
